<?php

return [
    'title' => 'Site structure', 'eyebrow' => 'Content',
    'types' => ['title' => 'Content types', 'description' => 'Schemas that define reusable structured materials.', 'empty' => 'No content types yet.', 'create' => 'Create content type', 'create_description' => 'Define one reusable schema using the seven supported field types.', 'fields_heading' => 'Field definitions', 'fields_help' => 'Each supported type is included once. Rename stable keys to match the domain.'],
    'materials' => ['title' => 'Materials', 'description' => 'Versioned structured content with review and publication.', 'empty' => 'No materials yet.', 'all_types' => 'All types', 'create' => 'Create material', 'edit' => 'Edit material', 'form_description' => 'Values are stored as typed data; this form contains no saved HTML.', 'choose_type' => 'Choose a content type', 'no_types' => 'Create a content type before adding a material.', 'fields_heading' => 'Structured values', 'no_file' => 'No file', 'no_relation' => 'No related material', 'read_only' => 'Your role has read-only access to this material.', 'current_state' => 'Current state: :status, revision #:revision.', 'preview' => 'Material preview', 'preview_description' => 'Protected preview of current revision #:revision.'],
    'description' => 'Published navigation, page metadata and managed redirects.',
    'navigation' => ['materials' => 'Materials', 'types' => 'Content types', 'site_structure' => 'Site structure', 'heading' => 'Navigation tree', 'help' => 'Order and nesting are saved as a versioned Content revision.', 'empty' => 'No navigation nodes yet.'],
    'seo' => ['heading' => 'SEO metadata', 'help' => 'Metadata is published together with this structure revision.', 'empty' => 'No SEO metadata yet.'],
    'workflow' => ['heading' => 'Editorial workflow'],
    'revisions' => ['heading' => 'Revision history', 'empty' => 'No revisions yet.'],
    'redirects' => ['heading' => 'Managed redirects', 'help' => 'Redirects are created by Content publication and cannot be forged manually.', 'empty' => 'No historical locators yet.', 'denied' => 'Your role cannot inspect redirects.'],
    'summary' => ['revision' => 'Current revision', 'status' => 'Status', 'published' => 'Published revision'],
    'fields' => ['label' => 'Label', 'parent' => 'Parent', 'position' => 'Order', 'target' => 'Target', 'visible' => 'Visible', 'remove' => 'Remove', 'key' => 'Key', 'version' => 'Version', 'fields' => 'Fields', 'type_key' => 'Type key', 'plural_label' => 'Plural label', 'description' => 'Description', 'type' => 'Type', 'required' => 'Required', 'title' => 'Title', 'status' => 'Status', 'revision' => 'Revision', 'actions' => 'Actions', 'locale' => 'Locale', 'slug' => 'Slug', 'visibility' => 'Visibility', 'author' => 'Author'],
    'field_types' => ['string' => 'String', 'text' => 'Text', 'number' => 'Number', 'boolean' => 'Boolean', 'date' => 'Date', 'file' => 'File', 'relation' => 'Relation'],
    'visibility' => ['public' => 'Public', 'private' => 'Private'], 'boolean' => ['yes' => 'Yes', 'no' => 'No'],
    'actions' => ['add_node' => 'Add navigation node', 'add_seo' => 'Add SEO entry', 'save' => 'Save draft', 'submit_review' => 'Submit for review', 'publish' => 'Publish', 'restore' => 'Restore this revision', 'create_type' => 'Create content type', 'create_material' => 'Create material', 'save_material' => 'Save new revision', 'back' => 'Back', 'filter' => 'Filter', 'continue' => 'Continue', 'preview' => 'Preview', 'unpublish' => 'Unpublish', 'open_public' => 'Open public page'],
    'messages' => ['saved' => 'Draft revision saved.', 'submitted' => 'Revision submitted for review.', 'published' => 'Revision published.', 'unpublished' => 'Material unpublished.', 'restored' => 'Previous revision restored as a new draft.', 'type_created' => 'Content type created.', 'material_created' => 'Material created.', 'material_saved' => 'A new material revision was saved.', 'stale' => 'The content changed in another request. Reload and try again.', 'rejected' => 'The operation failed closed: :reason.', 'historical' => 'Viewing historical revision #:revision.', 'reasons' => ['publication_projection_invalid' => 'Make referenced files public and publish related materials before publishing this revision.']],
];
